### ISSUE TITLE
亮色版？

### ISSUE THREAD

**Issue by FranklinYu** [CosmosAtlas/base16-danqing-scheme#1]
感謝作者的設計，中國風的配色很好看！如果能有暗色版就更好了。我日常會在亮色和暗色之間切換 😄

**Comment by CosmosAtlas** [comment]
不太清楚暗色版是什么意思，目前的主题已经是 dark theme 了。

如果需要在亮色和暗色切换的话，我新加入了一个亮色版本。本质上就是把 base16 的前 8 个颜色的顺序调换一下。

下面是示图

<img width="456" alt="image" src="https://user-images.githubusercontent.com/5738747/183109004-f48d9368-110a-4be0-85d9-1689cecd28de.png">

Repo 里面新加入了一个文件 `danqing-light.yaml`，可以用这个文件配合 builder/templates 生成亮色版本的主题。

在 schemes repo 中提了 pr，不过可能需要等一阵子

**Comment by FranklinYu** [comment]
是我說錯了。我想要的正是亮色版本。非常感謝！我用的 template 似乎很久不更新了，我自己去 PR。

如果此示圖也能加入 ReadMe，就更好了。

**Comment by FranklinYu** [comment]
用了幾天，感覺亮色版的對比度不如暗色版。比如，蟹殼青[在暗色下的對比度](https://webaim.org/resources/contrastchecker/?fcolor=8AB361&bcolor=2D302F)是 5.52，滿足 WCAG AA 的三個指標（AAA 過於嚴格，可以暫不理會）；其[在亮色下的對比度](https://webaim.org/resources/contrastchecker/?fcolor=8AB361&bcolor=FCFEFD)則僅有 2.38，不滿足任何一個指標……

有沒有什麼想法？是微調一下，還是另選別的顏色？

**Comment by CosmosAtlas** [comment]
https://www.w3.org/TR/WCAG20/#relativeluminancedef

按照这个的定义，绿色是 sRGB 中影响 luminance 最大的组成部分。而且按照 WCAG AA 的标准，大概测算了一下，其实很多颜色的选择都不达标。

目前用的是 *素* 这个颜色做的背景基准色彩，我后面尝试一下，能同时满足暗色和亮色背景的符合 WCAG AA 的水墨风格颜色有哪些，然后再看看有什么颜色是可以取舍的。

不过如果改变太大的话，可能会考虑重新命名一个新的 colorscheme 了（虽然目测会影响的人数几乎没有）。

**Comment by FranklinYu** [comment]
> 按照 WCAG AA 的标准，大概测算了一下，其实很多颜色的选择都不达标。

亮色主題就沒幾個達標的 😅 我個人感覺他 4.5 有點高了。我自己調了一下，超過 3.0 就基本可以看清了。亮色模式下，黃色可能會是主要難點。
